### PR TITLE
Fixed setup script and added isfile check to AceProcess constructor.

### PR DESCRIPTION
**Pull request by dantiston**

### CODE REVIEW

**Comment by goodmami** [comment]
Thanks!

You seem to have checked in the build/ subdirectory (I guess after running `setup.py build`, which is currently unnecessary anyway as there are no C extensions for pyDelphin that need to be built). Revert the change (so all the files aren't in the history), then add and commit *only* setup.py. I think you do this, but be careful you do this to the current state of your hosted fork; it will probably remove any uncommitted changes:

```bash
cp setup.py ~/setup.py.bak
git reset --hard HEAD^
mv ~/setup.py.bak setup.py
git add setup.py
git commit -m "Fix setup script."
```
See here: http://sethrobertson.github.io/GitFixUm/fixup.html

If that seems to involved, you can just remove your fork, re-fork pyDelphin, and re-add the change, only committing setup.py. This might be easier since you only have the one commit.

**Comment by dantiston** [comment]
I see the error now, yes. I was wondering what those files were... I've cleaned up my fork and added a gitignore. There's the change to setup.py, ace.py, and a simple ace.py test for the isfile check.

**Comment by goodmami** [comment]
Did you try the `git reset --hard HEAD^` command? It looks like all the build files are still in the history (added, then removed in a subsequent commit). I'm being picky, but I'd rather they didn't clutter up the history at all, in part because it increases the repository footprint unnecessarily. Btw, now the `HEAD^` part of the command won't work, since it's more than one commit prior. You may have to do `...HEAD~5` or something.

**Comment by dantiston** [comment]
Ohh, I see. I was sort of wondering why you had suggested using reset.

I didn’t. I’ll do that tomorrow and let you know.

--
T.J. Trimble

**Comment by goodmami** [comment]
Thanks! Like I said, it might be easier to just work off a fresh fork, unless you want to learn about `git reset` (probably a handy skill; I should figure it out sometime, too).

**Comment by goodmami** [comment]
This was covered by the last pull request. Closing.

**Pull request closed without merging**
